import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import dynamic from "next/dynamic";

const DeckMap = dynamic(() => import("~/components/DeckMap"), {
  ssr: false,
});

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  // console.log(data, "data");

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen">
        <DeckMap />
      </main>
    </>
  );
}
